//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Traderdata.Client.TerminalWEB.TerminalWebSVC {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/Traderdata.Server.App.TerminalWeb.DTO")]
    public partial class UserDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string LoginField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateDTO", Namespace="http://schemas.datacontract.org/2004/07/Traderdata.Server.App.TerminalWeb.DTO")]
    public partial class TemplateDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private System.Collections.Generic.List<Traderdata.Client.TerminalWEB.TerminalWebSVC.LayoutDTO> LayoutsField;
        
        private string NomeField;
        
        private int PeriodicidadeField;
        
        private int UsuarioIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Traderdata.Client.TerminalWEB.TerminalWebSVC.LayoutDTO> Layouts {
            get {
                return this.LayoutsField;
            }
            set {
                if ((object.ReferenceEquals(this.LayoutsField, value) != true)) {
                    this.LayoutsField = value;
                    this.RaisePropertyChanged("Layouts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Periodicidade {
            get {
                return this.PeriodicidadeField;
            }
            set {
                if ((this.PeriodicidadeField.Equals(value) != true)) {
                    this.PeriodicidadeField = value;
                    this.RaisePropertyChanged("Periodicidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LayoutDTO", Namespace="http://schemas.datacontract.org/2004/07/Traderdata.Server.App.TerminalWeb.DTO")]
    public partial class LayoutDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CorBordaCandleAltaField;
        
        private string CorBordaCandleBaixaField;
        
        private string CorCandleAltaField;
        
        private string CorCandleBaixaField;
        
        private string CorEscalaField;
        
        private string CorFundoField;
        
        private string CorGridField;
        
        private string CorVolumeField;
        
        private System.Nullable<bool> DarvaBoxField;
        
        private System.Nullable<double> EspacoADireitaDoGraficoField;
        
        private System.Nullable<double> EspacoAEsquerdaDoGraficoField;
        
        private System.Nullable<int> EstiloBarraField;
        
        private System.Nullable<int> EstiloPrecoField;
        
        private System.Nullable<double> EstiloPrecoParam1Field;
        
        private System.Nullable<double> EstiloPrecoParam2Field;
        
        private int FirstVisibleRecordField;
        
        private System.Nullable<bool> GradeHorizontalField;
        
        private System.Nullable<bool> GradeVerticalField;
        
        private System.Nullable<int> GraficoIdField;
        
        private int IdField;
        
        private int IndexField;
        
        private System.Collections.Generic.List<Traderdata.Client.TerminalWEB.TerminalWebSVC.IndicadorDTO> IndicadoresField;
        
        private System.Collections.Generic.List<Traderdata.Client.TerminalWEB.TerminalWebSVC.ObjetoEstudoDTO> ObjetosField;
        
        private System.Collections.Generic.List<Traderdata.Client.TerminalWEB.TerminalWebSVC.PainelDTO> PaineisField;
        
        private System.Nullable<bool> PainelInfoField;
        
        private int PeriodicidadeField;
        
        private System.Nullable<int> PosicaoEscalaField;
        
        private System.Nullable<int> PrecisaoEscalaField;
        
        private System.Nullable<int> TemplateIdField;
        
        private System.Nullable<int> TipoEscalaField;
        
        private string TipoVolumeField;
        
        private System.Nullable<bool> UsarCoresAltaBaixaVolumeField;
        
        private int VisibleRecordsField;
        
        private int VolumeStrokeThicknessField;
        
        private bool ZoomRealtimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorBordaCandleAlta {
            get {
                return this.CorBordaCandleAltaField;
            }
            set {
                if ((object.ReferenceEquals(this.CorBordaCandleAltaField, value) != true)) {
                    this.CorBordaCandleAltaField = value;
                    this.RaisePropertyChanged("CorBordaCandleAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorBordaCandleBaixa {
            get {
                return this.CorBordaCandleBaixaField;
            }
            set {
                if ((object.ReferenceEquals(this.CorBordaCandleBaixaField, value) != true)) {
                    this.CorBordaCandleBaixaField = value;
                    this.RaisePropertyChanged("CorBordaCandleBaixa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorCandleAlta {
            get {
                return this.CorCandleAltaField;
            }
            set {
                if ((object.ReferenceEquals(this.CorCandleAltaField, value) != true)) {
                    this.CorCandleAltaField = value;
                    this.RaisePropertyChanged("CorCandleAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorCandleBaixa {
            get {
                return this.CorCandleBaixaField;
            }
            set {
                if ((object.ReferenceEquals(this.CorCandleBaixaField, value) != true)) {
                    this.CorCandleBaixaField = value;
                    this.RaisePropertyChanged("CorCandleBaixa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorEscala {
            get {
                return this.CorEscalaField;
            }
            set {
                if ((object.ReferenceEquals(this.CorEscalaField, value) != true)) {
                    this.CorEscalaField = value;
                    this.RaisePropertyChanged("CorEscala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorFundo {
            get {
                return this.CorFundoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorFundoField, value) != true)) {
                    this.CorFundoField = value;
                    this.RaisePropertyChanged("CorFundo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorGrid {
            get {
                return this.CorGridField;
            }
            set {
                if ((object.ReferenceEquals(this.CorGridField, value) != true)) {
                    this.CorGridField = value;
                    this.RaisePropertyChanged("CorGrid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorVolume {
            get {
                return this.CorVolumeField;
            }
            set {
                if ((object.ReferenceEquals(this.CorVolumeField, value) != true)) {
                    this.CorVolumeField = value;
                    this.RaisePropertyChanged("CorVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DarvaBox {
            get {
                return this.DarvaBoxField;
            }
            set {
                if ((this.DarvaBoxField.Equals(value) != true)) {
                    this.DarvaBoxField = value;
                    this.RaisePropertyChanged("DarvaBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EspacoADireitaDoGrafico {
            get {
                return this.EspacoADireitaDoGraficoField;
            }
            set {
                if ((this.EspacoADireitaDoGraficoField.Equals(value) != true)) {
                    this.EspacoADireitaDoGraficoField = value;
                    this.RaisePropertyChanged("EspacoADireitaDoGrafico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EspacoAEsquerdaDoGrafico {
            get {
                return this.EspacoAEsquerdaDoGraficoField;
            }
            set {
                if ((this.EspacoAEsquerdaDoGraficoField.Equals(value) != true)) {
                    this.EspacoAEsquerdaDoGraficoField = value;
                    this.RaisePropertyChanged("EspacoAEsquerdaDoGrafico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EstiloBarra {
            get {
                return this.EstiloBarraField;
            }
            set {
                if ((this.EstiloBarraField.Equals(value) != true)) {
                    this.EstiloBarraField = value;
                    this.RaisePropertyChanged("EstiloBarra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EstiloPreco {
            get {
                return this.EstiloPrecoField;
            }
            set {
                if ((this.EstiloPrecoField.Equals(value) != true)) {
                    this.EstiloPrecoField = value;
                    this.RaisePropertyChanged("EstiloPreco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EstiloPrecoParam1 {
            get {
                return this.EstiloPrecoParam1Field;
            }
            set {
                if ((this.EstiloPrecoParam1Field.Equals(value) != true)) {
                    this.EstiloPrecoParam1Field = value;
                    this.RaisePropertyChanged("EstiloPrecoParam1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EstiloPrecoParam2 {
            get {
                return this.EstiloPrecoParam2Field;
            }
            set {
                if ((this.EstiloPrecoParam2Field.Equals(value) != true)) {
                    this.EstiloPrecoParam2Field = value;
                    this.RaisePropertyChanged("EstiloPrecoParam2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirstVisibleRecord {
            get {
                return this.FirstVisibleRecordField;
            }
            set {
                if ((this.FirstVisibleRecordField.Equals(value) != true)) {
                    this.FirstVisibleRecordField = value;
                    this.RaisePropertyChanged("FirstVisibleRecord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> GradeHorizontal {
            get {
                return this.GradeHorizontalField;
            }
            set {
                if ((this.GradeHorizontalField.Equals(value) != true)) {
                    this.GradeHorizontalField = value;
                    this.RaisePropertyChanged("GradeHorizontal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> GradeVertical {
            get {
                return this.GradeVerticalField;
            }
            set {
                if ((this.GradeVerticalField.Equals(value) != true)) {
                    this.GradeVerticalField = value;
                    this.RaisePropertyChanged("GradeVertical");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GraficoId {
            get {
                return this.GraficoIdField;
            }
            set {
                if ((this.GraficoIdField.Equals(value) != true)) {
                    this.GraficoIdField = value;
                    this.RaisePropertyChanged("GraficoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Traderdata.Client.TerminalWEB.TerminalWebSVC.IndicadorDTO> Indicadores {
            get {
                return this.IndicadoresField;
            }
            set {
                if ((object.ReferenceEquals(this.IndicadoresField, value) != true)) {
                    this.IndicadoresField = value;
                    this.RaisePropertyChanged("Indicadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Traderdata.Client.TerminalWEB.TerminalWebSVC.ObjetoEstudoDTO> Objetos {
            get {
                return this.ObjetosField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjetosField, value) != true)) {
                    this.ObjetosField = value;
                    this.RaisePropertyChanged("Objetos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Traderdata.Client.TerminalWEB.TerminalWebSVC.PainelDTO> Paineis {
            get {
                return this.PaineisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaineisField, value) != true)) {
                    this.PaineisField = value;
                    this.RaisePropertyChanged("Paineis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> PainelInfo {
            get {
                return this.PainelInfoField;
            }
            set {
                if ((this.PainelInfoField.Equals(value) != true)) {
                    this.PainelInfoField = value;
                    this.RaisePropertyChanged("PainelInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Periodicidade {
            get {
                return this.PeriodicidadeField;
            }
            set {
                if ((this.PeriodicidadeField.Equals(value) != true)) {
                    this.PeriodicidadeField = value;
                    this.RaisePropertyChanged("Periodicidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PosicaoEscala {
            get {
                return this.PosicaoEscalaField;
            }
            set {
                if ((this.PosicaoEscalaField.Equals(value) != true)) {
                    this.PosicaoEscalaField = value;
                    this.RaisePropertyChanged("PosicaoEscala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PrecisaoEscala {
            get {
                return this.PrecisaoEscalaField;
            }
            set {
                if ((this.PrecisaoEscalaField.Equals(value) != true)) {
                    this.PrecisaoEscalaField = value;
                    this.RaisePropertyChanged("PrecisaoEscala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TemplateId {
            get {
                return this.TemplateIdField;
            }
            set {
                if ((this.TemplateIdField.Equals(value) != true)) {
                    this.TemplateIdField = value;
                    this.RaisePropertyChanged("TemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoEscala {
            get {
                return this.TipoEscalaField;
            }
            set {
                if ((this.TipoEscalaField.Equals(value) != true)) {
                    this.TipoEscalaField = value;
                    this.RaisePropertyChanged("TipoEscala");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoVolume {
            get {
                return this.TipoVolumeField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoVolumeField, value) != true)) {
                    this.TipoVolumeField = value;
                    this.RaisePropertyChanged("TipoVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> UsarCoresAltaBaixaVolume {
            get {
                return this.UsarCoresAltaBaixaVolumeField;
            }
            set {
                if ((this.UsarCoresAltaBaixaVolumeField.Equals(value) != true)) {
                    this.UsarCoresAltaBaixaVolumeField = value;
                    this.RaisePropertyChanged("UsarCoresAltaBaixaVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VisibleRecords {
            get {
                return this.VisibleRecordsField;
            }
            set {
                if ((this.VisibleRecordsField.Equals(value) != true)) {
                    this.VisibleRecordsField = value;
                    this.RaisePropertyChanged("VisibleRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VolumeStrokeThickness {
            get {
                return this.VolumeStrokeThicknessField;
            }
            set {
                if ((this.VolumeStrokeThicknessField.Equals(value) != true)) {
                    this.VolumeStrokeThicknessField = value;
                    this.RaisePropertyChanged("VolumeStrokeThickness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ZoomRealtime {
            get {
                return this.ZoomRealtimeField;
            }
            set {
                if ((this.ZoomRealtimeField.Equals(value) != true)) {
                    this.ZoomRealtimeField = value;
                    this.RaisePropertyChanged("ZoomRealtime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndicadorDTO", Namespace="http://schemas.datacontract.org/2004/07/Traderdata.Server.App.TerminalWeb.DTO", IsReference=true)]
    public partial class IndicadorDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CorField;
        
        private string CorFilha1Field;
        
        private string CorFilha2Field;
        
        private System.Nullable<int> EspessuraField;
        
        private System.Nullable<int> EspessuraFilha1Field;
        
        private System.Nullable<int> EspessuraFilha2Field;
        
        private int IdField;
        
        private System.Nullable<int> IndexPainelField;
        
        private System.Nullable<int> LayoutIdField;
        
        private string NameField;
        
        private string ParametrosField;
        
        private System.Nullable<int> TipoIndicadorField;
        
        private System.Nullable<int> TipoLinhaField;
        
        private System.Nullable<int> TipoLinhaFilha1Field;
        
        private System.Nullable<int> TipoLinhaFilha2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cor {
            get {
                return this.CorField;
            }
            set {
                if ((object.ReferenceEquals(this.CorField, value) != true)) {
                    this.CorField = value;
                    this.RaisePropertyChanged("Cor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorFilha1 {
            get {
                return this.CorFilha1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CorFilha1Field, value) != true)) {
                    this.CorFilha1Field = value;
                    this.RaisePropertyChanged("CorFilha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorFilha2 {
            get {
                return this.CorFilha2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CorFilha2Field, value) != true)) {
                    this.CorFilha2Field = value;
                    this.RaisePropertyChanged("CorFilha2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Espessura {
            get {
                return this.EspessuraField;
            }
            set {
                if ((this.EspessuraField.Equals(value) != true)) {
                    this.EspessuraField = value;
                    this.RaisePropertyChanged("Espessura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EspessuraFilha1 {
            get {
                return this.EspessuraFilha1Field;
            }
            set {
                if ((this.EspessuraFilha1Field.Equals(value) != true)) {
                    this.EspessuraFilha1Field = value;
                    this.RaisePropertyChanged("EspessuraFilha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EspessuraFilha2 {
            get {
                return this.EspessuraFilha2Field;
            }
            set {
                if ((this.EspessuraFilha2Field.Equals(value) != true)) {
                    this.EspessuraFilha2Field = value;
                    this.RaisePropertyChanged("EspessuraFilha2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IndexPainel {
            get {
                return this.IndexPainelField;
            }
            set {
                if ((this.IndexPainelField.Equals(value) != true)) {
                    this.IndexPainelField = value;
                    this.RaisePropertyChanged("IndexPainel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LayoutId {
            get {
                return this.LayoutIdField;
            }
            set {
                if ((this.LayoutIdField.Equals(value) != true)) {
                    this.LayoutIdField = value;
                    this.RaisePropertyChanged("LayoutId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parametros {
            get {
                return this.ParametrosField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametrosField, value) != true)) {
                    this.ParametrosField = value;
                    this.RaisePropertyChanged("Parametros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoIndicador {
            get {
                return this.TipoIndicadorField;
            }
            set {
                if ((this.TipoIndicadorField.Equals(value) != true)) {
                    this.TipoIndicadorField = value;
                    this.RaisePropertyChanged("TipoIndicador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoLinha {
            get {
                return this.TipoLinhaField;
            }
            set {
                if ((this.TipoLinhaField.Equals(value) != true)) {
                    this.TipoLinhaField = value;
                    this.RaisePropertyChanged("TipoLinha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoLinhaFilha1 {
            get {
                return this.TipoLinhaFilha1Field;
            }
            set {
                if ((this.TipoLinhaFilha1Field.Equals(value) != true)) {
                    this.TipoLinhaFilha1Field = value;
                    this.RaisePropertyChanged("TipoLinhaFilha1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoLinhaFilha2 {
            get {
                return this.TipoLinhaFilha2Field;
            }
            set {
                if ((this.TipoLinhaFilha2Field.Equals(value) != true)) {
                    this.TipoLinhaFilha2Field = value;
                    this.RaisePropertyChanged("TipoLinhaFilha2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjetoEstudoDTO", Namespace="http://schemas.datacontract.org/2004/07/Traderdata.Server.App.TerminalWeb.DTO")]
    public partial class ObjetoEstudoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CorObjetoField;
        
        private System.Nullable<int> EspessuraField;
        
        private int IdField;
        
        private int IndexPainelField;
        
        private System.Nullable<bool> InfinitaADireitaField;
        
        private int LayoutIdField;
        
        private System.Nullable<bool> MagneticaField;
        
        private string ParametrosField;
        
        private int RecordFinalField;
        
        private int RecordInicialField;
        
        private System.Nullable<int> TamanhoTextoField;
        
        private string TextoField;
        
        private System.Nullable<int> TipoLinhaField;
        
        private int TipoObjetoField;
        
        private System.Nullable<decimal> ValorErrorChannelField;
        
        private double ValorFinalField;
        
        private double ValorInicialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorObjeto {
            get {
                return this.CorObjetoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorObjetoField, value) != true)) {
                    this.CorObjetoField = value;
                    this.RaisePropertyChanged("CorObjeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Espessura {
            get {
                return this.EspessuraField;
            }
            set {
                if ((this.EspessuraField.Equals(value) != true)) {
                    this.EspessuraField = value;
                    this.RaisePropertyChanged("Espessura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IndexPainel {
            get {
                return this.IndexPainelField;
            }
            set {
                if ((this.IndexPainelField.Equals(value) != true)) {
                    this.IndexPainelField = value;
                    this.RaisePropertyChanged("IndexPainel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> InfinitaADireita {
            get {
                return this.InfinitaADireitaField;
            }
            set {
                if ((this.InfinitaADireitaField.Equals(value) != true)) {
                    this.InfinitaADireitaField = value;
                    this.RaisePropertyChanged("InfinitaADireita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LayoutId {
            get {
                return this.LayoutIdField;
            }
            set {
                if ((this.LayoutIdField.Equals(value) != true)) {
                    this.LayoutIdField = value;
                    this.RaisePropertyChanged("LayoutId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Magnetica {
            get {
                return this.MagneticaField;
            }
            set {
                if ((this.MagneticaField.Equals(value) != true)) {
                    this.MagneticaField = value;
                    this.RaisePropertyChanged("Magnetica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parametros {
            get {
                return this.ParametrosField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametrosField, value) != true)) {
                    this.ParametrosField = value;
                    this.RaisePropertyChanged("Parametros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordFinal {
            get {
                return this.RecordFinalField;
            }
            set {
                if ((this.RecordFinalField.Equals(value) != true)) {
                    this.RecordFinalField = value;
                    this.RaisePropertyChanged("RecordFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordInicial {
            get {
                return this.RecordInicialField;
            }
            set {
                if ((this.RecordInicialField.Equals(value) != true)) {
                    this.RecordInicialField = value;
                    this.RaisePropertyChanged("RecordInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TamanhoTexto {
            get {
                return this.TamanhoTextoField;
            }
            set {
                if ((this.TamanhoTextoField.Equals(value) != true)) {
                    this.TamanhoTextoField = value;
                    this.RaisePropertyChanged("TamanhoTexto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoLinha {
            get {
                return this.TipoLinhaField;
            }
            set {
                if ((this.TipoLinhaField.Equals(value) != true)) {
                    this.TipoLinhaField = value;
                    this.RaisePropertyChanged("TipoLinha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoObjeto {
            get {
                return this.TipoObjetoField;
            }
            set {
                if ((this.TipoObjetoField.Equals(value) != true)) {
                    this.TipoObjetoField = value;
                    this.RaisePropertyChanged("TipoObjeto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorErrorChannel {
            get {
                return this.ValorErrorChannelField;
            }
            set {
                if ((this.ValorErrorChannelField.Equals(value) != true)) {
                    this.ValorErrorChannelField = value;
                    this.RaisePropertyChanged("ValorErrorChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorFinal {
            get {
                return this.ValorFinalField;
            }
            set {
                if ((this.ValorFinalField.Equals(value) != true)) {
                    this.ValorFinalField = value;
                    this.RaisePropertyChanged("ValorFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorInicial {
            get {
                return this.ValorInicialField;
            }
            set {
                if ((this.ValorInicialField.Equals(value) != true)) {
                    this.ValorInicialField = value;
                    this.RaisePropertyChanged("ValorInicial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PainelDTO", Namespace="http://schemas.datacontract.org/2004/07/Traderdata.Server.App.TerminalWeb.DTO")]
    public partial class PainelDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AlturaField;
        
        private int IdField;
        
        private int IndexField;
        
        private int LayoutIdField;
        
        private string StatusField;
        
        private string TipoPainelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Altura {
            get {
                return this.AlturaField;
            }
            set {
                if ((this.AlturaField.Equals(value) != true)) {
                    this.AlturaField = value;
                    this.RaisePropertyChanged("Altura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LayoutId {
            get {
                return this.LayoutIdField;
            }
            set {
                if ((this.LayoutIdField.Equals(value) != true)) {
                    this.LayoutIdField = value;
                    this.RaisePropertyChanged("LayoutId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPainel {
            get {
                return this.TipoPainelField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPainelField, value) != true)) {
                    this.TipoPainelField = value;
                    this.RaisePropertyChanged("TipoPainel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GraficoDTO", Namespace="http://schemas.datacontract.org/2004/07/Traderdata.Server.App.TerminalWeb.DTO")]
    public partial class GraficoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AtivoField;
        
        private System.DateTime DataCadastroField;
        
        private int HeightField;
        
        private int IdField;
        
        private System.Collections.Generic.List<Traderdata.Client.TerminalWEB.TerminalWebSVC.LayoutDTO> LayoutsField;
        
        private int LeftField;
        
        private int PeriodicidadeField;
        
        private int TopField;
        
        private int UsuarioIdField;
        
        private int WidthField;
        
        private int WorkspaceIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((object.ReferenceEquals(this.AtivoField, value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Traderdata.Client.TerminalWEB.TerminalWebSVC.LayoutDTO> Layouts {
            get {
                return this.LayoutsField;
            }
            set {
                if ((object.ReferenceEquals(this.LayoutsField, value) != true)) {
                    this.LayoutsField = value;
                    this.RaisePropertyChanged("Layouts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Left {
            get {
                return this.LeftField;
            }
            set {
                if ((this.LeftField.Equals(value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Periodicidade {
            get {
                return this.PeriodicidadeField;
            }
            set {
                if ((this.PeriodicidadeField.Equals(value) != true)) {
                    this.PeriodicidadeField = value;
                    this.RaisePropertyChanged("Periodicidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Top {
            get {
                return this.TopField;
            }
            set {
                if ((this.TopField.Equals(value) != true)) {
                    this.TopField = value;
                    this.RaisePropertyChanged("Top");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkspaceId {
            get {
                return this.WorkspaceIdField;
            }
            set {
                if ((this.WorkspaceIdField.Equals(value) != true)) {
                    this.WorkspaceIdField = value;
                    this.RaisePropertyChanged("WorkspaceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TerminalWebSVC.ITerminalWeb")]
    public interface ITerminalWeb {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITerminalWeb/LoginOrInsertUser", ReplyAction="http://tempuri.org/ITerminalWeb/LoginOrInsertUserResponse")]
        System.IAsyncResult BeginLoginOrInsertUser(string login, System.AsyncCallback callback, object asyncState);
        
        Traderdata.Client.TerminalWEB.TerminalWebSVC.UserDTO EndLoginOrInsertUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITerminalWeb/GetTemplateFake", ReplyAction="http://tempuri.org/ITerminalWeb/GetTemplateFakeResponse")]
        System.IAsyncResult BeginGetTemplateFake(System.AsyncCallback callback, object asyncState);
        
        Traderdata.Client.TerminalWEB.TerminalWebSVC.TemplateDTO EndGetTemplateFake(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITerminalWeb/GetGraficoFake", ReplyAction="http://tempuri.org/ITerminalWeb/GetGraficoFakeResponse")]
        System.IAsyncResult BeginGetGraficoFake(System.AsyncCallback callback, object asyncState);
        
        Traderdata.Client.TerminalWEB.TerminalWebSVC.GraficoDTO EndGetGraficoFake(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITerminalWeb/GetObjetoFake", ReplyAction="http://tempuri.org/ITerminalWeb/GetObjetoFakeResponse")]
        System.IAsyncResult BeginGetObjetoFake(System.AsyncCallback callback, object asyncState);
        
        Traderdata.Client.TerminalWEB.TerminalWebSVC.ObjetoEstudoDTO EndGetObjetoFake(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITerminalWeb/GetIndicatorFake", ReplyAction="http://tempuri.org/ITerminalWeb/GetIndicatorFakeResponse")]
        System.IAsyncResult BeginGetIndicatorFake(System.AsyncCallback callback, object asyncState);
        
        Traderdata.Client.TerminalWEB.TerminalWebSVC.IndicadorDTO EndGetIndicatorFake(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITerminalWebChannel : Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginOrInsertUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginOrInsertUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Traderdata.Client.TerminalWEB.TerminalWebSVC.UserDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Traderdata.Client.TerminalWEB.TerminalWebSVC.UserDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTemplateFakeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTemplateFakeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Traderdata.Client.TerminalWEB.TerminalWebSVC.TemplateDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Traderdata.Client.TerminalWEB.TerminalWebSVC.TemplateDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetGraficoFakeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetGraficoFakeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Traderdata.Client.TerminalWEB.TerminalWebSVC.GraficoDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Traderdata.Client.TerminalWEB.TerminalWebSVC.GraficoDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetObjetoFakeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetObjetoFakeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Traderdata.Client.TerminalWEB.TerminalWebSVC.ObjetoEstudoDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ObjetoEstudoDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetIndicatorFakeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetIndicatorFakeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Traderdata.Client.TerminalWEB.TerminalWebSVC.IndicadorDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Traderdata.Client.TerminalWEB.TerminalWebSVC.IndicadorDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TerminalWebClient : System.ServiceModel.ClientBase<Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb>, Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb {
        
        private BeginOperationDelegate onBeginLoginOrInsertUserDelegate;
        
        private EndOperationDelegate onEndLoginOrInsertUserDelegate;
        
        private System.Threading.SendOrPostCallback onLoginOrInsertUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTemplateFakeDelegate;
        
        private EndOperationDelegate onEndGetTemplateFakeDelegate;
        
        private System.Threading.SendOrPostCallback onGetTemplateFakeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetGraficoFakeDelegate;
        
        private EndOperationDelegate onEndGetGraficoFakeDelegate;
        
        private System.Threading.SendOrPostCallback onGetGraficoFakeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetObjetoFakeDelegate;
        
        private EndOperationDelegate onEndGetObjetoFakeDelegate;
        
        private System.Threading.SendOrPostCallback onGetObjetoFakeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetIndicatorFakeDelegate;
        
        private EndOperationDelegate onEndGetIndicatorFakeDelegate;
        
        private System.Threading.SendOrPostCallback onGetIndicatorFakeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public TerminalWebClient() {
        }
        
        public TerminalWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TerminalWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoginOrInsertUserCompletedEventArgs> LoginOrInsertUserCompleted;
        
        public event System.EventHandler<GetTemplateFakeCompletedEventArgs> GetTemplateFakeCompleted;
        
        public event System.EventHandler<GetGraficoFakeCompletedEventArgs> GetGraficoFakeCompleted;
        
        public event System.EventHandler<GetObjetoFakeCompletedEventArgs> GetObjetoFakeCompleted;
        
        public event System.EventHandler<GetIndicatorFakeCompletedEventArgs> GetIndicatorFakeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb.BeginLoginOrInsertUser(string login, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoginOrInsertUser(login, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Traderdata.Client.TerminalWEB.TerminalWebSVC.UserDTO Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb.EndLoginOrInsertUser(System.IAsyncResult result) {
            return base.Channel.EndLoginOrInsertUser(result);
        }
        
        private System.IAsyncResult OnBeginLoginOrInsertUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            return ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb)(this)).BeginLoginOrInsertUser(login, callback, asyncState);
        }
        
        private object[] OnEndLoginOrInsertUser(System.IAsyncResult result) {
            Traderdata.Client.TerminalWEB.TerminalWebSVC.UserDTO retVal = ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb)(this)).EndLoginOrInsertUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginOrInsertUserCompleted(object state) {
            if ((this.LoginOrInsertUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginOrInsertUserCompleted(this, new LoginOrInsertUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginOrInsertUserAsync(string login) {
            this.LoginOrInsertUserAsync(login, null);
        }
        
        public void LoginOrInsertUserAsync(string login, object userState) {
            if ((this.onBeginLoginOrInsertUserDelegate == null)) {
                this.onBeginLoginOrInsertUserDelegate = new BeginOperationDelegate(this.OnBeginLoginOrInsertUser);
            }
            if ((this.onEndLoginOrInsertUserDelegate == null)) {
                this.onEndLoginOrInsertUserDelegate = new EndOperationDelegate(this.OnEndLoginOrInsertUser);
            }
            if ((this.onLoginOrInsertUserCompletedDelegate == null)) {
                this.onLoginOrInsertUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginOrInsertUserCompleted);
            }
            base.InvokeAsync(this.onBeginLoginOrInsertUserDelegate, new object[] {
                        login}, this.onEndLoginOrInsertUserDelegate, this.onLoginOrInsertUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb.BeginGetTemplateFake(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTemplateFake(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Traderdata.Client.TerminalWEB.TerminalWebSVC.TemplateDTO Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb.EndGetTemplateFake(System.IAsyncResult result) {
            return base.Channel.EndGetTemplateFake(result);
        }
        
        private System.IAsyncResult OnBeginGetTemplateFake(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb)(this)).BeginGetTemplateFake(callback, asyncState);
        }
        
        private object[] OnEndGetTemplateFake(System.IAsyncResult result) {
            Traderdata.Client.TerminalWEB.TerminalWebSVC.TemplateDTO retVal = ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb)(this)).EndGetTemplateFake(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTemplateFakeCompleted(object state) {
            if ((this.GetTemplateFakeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTemplateFakeCompleted(this, new GetTemplateFakeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTemplateFakeAsync() {
            this.GetTemplateFakeAsync(null);
        }
        
        public void GetTemplateFakeAsync(object userState) {
            if ((this.onBeginGetTemplateFakeDelegate == null)) {
                this.onBeginGetTemplateFakeDelegate = new BeginOperationDelegate(this.OnBeginGetTemplateFake);
            }
            if ((this.onEndGetTemplateFakeDelegate == null)) {
                this.onEndGetTemplateFakeDelegate = new EndOperationDelegate(this.OnEndGetTemplateFake);
            }
            if ((this.onGetTemplateFakeCompletedDelegate == null)) {
                this.onGetTemplateFakeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTemplateFakeCompleted);
            }
            base.InvokeAsync(this.onBeginGetTemplateFakeDelegate, null, this.onEndGetTemplateFakeDelegate, this.onGetTemplateFakeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb.BeginGetGraficoFake(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetGraficoFake(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Traderdata.Client.TerminalWEB.TerminalWebSVC.GraficoDTO Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb.EndGetGraficoFake(System.IAsyncResult result) {
            return base.Channel.EndGetGraficoFake(result);
        }
        
        private System.IAsyncResult OnBeginGetGraficoFake(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb)(this)).BeginGetGraficoFake(callback, asyncState);
        }
        
        private object[] OnEndGetGraficoFake(System.IAsyncResult result) {
            Traderdata.Client.TerminalWEB.TerminalWebSVC.GraficoDTO retVal = ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb)(this)).EndGetGraficoFake(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetGraficoFakeCompleted(object state) {
            if ((this.GetGraficoFakeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetGraficoFakeCompleted(this, new GetGraficoFakeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetGraficoFakeAsync() {
            this.GetGraficoFakeAsync(null);
        }
        
        public void GetGraficoFakeAsync(object userState) {
            if ((this.onBeginGetGraficoFakeDelegate == null)) {
                this.onBeginGetGraficoFakeDelegate = new BeginOperationDelegate(this.OnBeginGetGraficoFake);
            }
            if ((this.onEndGetGraficoFakeDelegate == null)) {
                this.onEndGetGraficoFakeDelegate = new EndOperationDelegate(this.OnEndGetGraficoFake);
            }
            if ((this.onGetGraficoFakeCompletedDelegate == null)) {
                this.onGetGraficoFakeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetGraficoFakeCompleted);
            }
            base.InvokeAsync(this.onBeginGetGraficoFakeDelegate, null, this.onEndGetGraficoFakeDelegate, this.onGetGraficoFakeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb.BeginGetObjetoFake(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetObjetoFake(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Traderdata.Client.TerminalWEB.TerminalWebSVC.ObjetoEstudoDTO Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb.EndGetObjetoFake(System.IAsyncResult result) {
            return base.Channel.EndGetObjetoFake(result);
        }
        
        private System.IAsyncResult OnBeginGetObjetoFake(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb)(this)).BeginGetObjetoFake(callback, asyncState);
        }
        
        private object[] OnEndGetObjetoFake(System.IAsyncResult result) {
            Traderdata.Client.TerminalWEB.TerminalWebSVC.ObjetoEstudoDTO retVal = ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb)(this)).EndGetObjetoFake(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetObjetoFakeCompleted(object state) {
            if ((this.GetObjetoFakeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetObjetoFakeCompleted(this, new GetObjetoFakeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetObjetoFakeAsync() {
            this.GetObjetoFakeAsync(null);
        }
        
        public void GetObjetoFakeAsync(object userState) {
            if ((this.onBeginGetObjetoFakeDelegate == null)) {
                this.onBeginGetObjetoFakeDelegate = new BeginOperationDelegate(this.OnBeginGetObjetoFake);
            }
            if ((this.onEndGetObjetoFakeDelegate == null)) {
                this.onEndGetObjetoFakeDelegate = new EndOperationDelegate(this.OnEndGetObjetoFake);
            }
            if ((this.onGetObjetoFakeCompletedDelegate == null)) {
                this.onGetObjetoFakeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetObjetoFakeCompleted);
            }
            base.InvokeAsync(this.onBeginGetObjetoFakeDelegate, null, this.onEndGetObjetoFakeDelegate, this.onGetObjetoFakeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb.BeginGetIndicatorFake(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetIndicatorFake(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Traderdata.Client.TerminalWEB.TerminalWebSVC.IndicadorDTO Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb.EndGetIndicatorFake(System.IAsyncResult result) {
            return base.Channel.EndGetIndicatorFake(result);
        }
        
        private System.IAsyncResult OnBeginGetIndicatorFake(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb)(this)).BeginGetIndicatorFake(callback, asyncState);
        }
        
        private object[] OnEndGetIndicatorFake(System.IAsyncResult result) {
            Traderdata.Client.TerminalWEB.TerminalWebSVC.IndicadorDTO retVal = ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb)(this)).EndGetIndicatorFake(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetIndicatorFakeCompleted(object state) {
            if ((this.GetIndicatorFakeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetIndicatorFakeCompleted(this, new GetIndicatorFakeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetIndicatorFakeAsync() {
            this.GetIndicatorFakeAsync(null);
        }
        
        public void GetIndicatorFakeAsync(object userState) {
            if ((this.onBeginGetIndicatorFakeDelegate == null)) {
                this.onBeginGetIndicatorFakeDelegate = new BeginOperationDelegate(this.OnBeginGetIndicatorFake);
            }
            if ((this.onEndGetIndicatorFakeDelegate == null)) {
                this.onEndGetIndicatorFakeDelegate = new EndOperationDelegate(this.OnEndGetIndicatorFake);
            }
            if ((this.onGetIndicatorFakeCompletedDelegate == null)) {
                this.onGetIndicatorFakeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetIndicatorFakeCompleted);
            }
            base.InvokeAsync(this.onBeginGetIndicatorFakeDelegate, null, this.onEndGetIndicatorFakeDelegate, this.onGetIndicatorFakeCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb CreateChannel() {
            return new TerminalWebClientChannel(this);
        }
        
        private class TerminalWebClientChannel : ChannelBase<Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb>, Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb {
            
            public TerminalWebClientChannel(System.ServiceModel.ClientBase<Traderdata.Client.TerminalWEB.TerminalWebSVC.ITerminalWeb> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLoginOrInsertUser(string login, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = login;
                System.IAsyncResult _result = base.BeginInvoke("LoginOrInsertUser", _args, callback, asyncState);
                return _result;
            }
            
            public Traderdata.Client.TerminalWEB.TerminalWebSVC.UserDTO EndLoginOrInsertUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                Traderdata.Client.TerminalWEB.TerminalWebSVC.UserDTO _result = ((Traderdata.Client.TerminalWEB.TerminalWebSVC.UserDTO)(base.EndInvoke("LoginOrInsertUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTemplateFake(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTemplateFake", _args, callback, asyncState);
                return _result;
            }
            
            public Traderdata.Client.TerminalWEB.TerminalWebSVC.TemplateDTO EndGetTemplateFake(System.IAsyncResult result) {
                object[] _args = new object[0];
                Traderdata.Client.TerminalWEB.TerminalWebSVC.TemplateDTO _result = ((Traderdata.Client.TerminalWEB.TerminalWebSVC.TemplateDTO)(base.EndInvoke("GetTemplateFake", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetGraficoFake(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetGraficoFake", _args, callback, asyncState);
                return _result;
            }
            
            public Traderdata.Client.TerminalWEB.TerminalWebSVC.GraficoDTO EndGetGraficoFake(System.IAsyncResult result) {
                object[] _args = new object[0];
                Traderdata.Client.TerminalWEB.TerminalWebSVC.GraficoDTO _result = ((Traderdata.Client.TerminalWEB.TerminalWebSVC.GraficoDTO)(base.EndInvoke("GetGraficoFake", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetObjetoFake(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetObjetoFake", _args, callback, asyncState);
                return _result;
            }
            
            public Traderdata.Client.TerminalWEB.TerminalWebSVC.ObjetoEstudoDTO EndGetObjetoFake(System.IAsyncResult result) {
                object[] _args = new object[0];
                Traderdata.Client.TerminalWEB.TerminalWebSVC.ObjetoEstudoDTO _result = ((Traderdata.Client.TerminalWEB.TerminalWebSVC.ObjetoEstudoDTO)(base.EndInvoke("GetObjetoFake", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetIndicatorFake(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetIndicatorFake", _args, callback, asyncState);
                return _result;
            }
            
            public Traderdata.Client.TerminalWEB.TerminalWebSVC.IndicadorDTO EndGetIndicatorFake(System.IAsyncResult result) {
                object[] _args = new object[0];
                Traderdata.Client.TerminalWEB.TerminalWebSVC.IndicadorDTO _result = ((Traderdata.Client.TerminalWEB.TerminalWebSVC.IndicadorDTO)(base.EndInvoke("GetIndicatorFake", _args, result)));
                return _result;
            }
        }
    }
}
